sudo: false
language: node_js
node_js: 6.2
services: mongodb
script:
- npm test -- -- --timeout 10000
after_success:
- 'cat coverage/lcov.info | ./node_modules/.bin/codecov'
- 'cat coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter'
cache:
  directories:
  - $HOME/.nvm
